happiness_star/urls.py
from django.conf.urls import url
from . import views

app_name = 'happiness_star'

urlpatterns = [
    url('^$', views.StarElmView.as_view(), name='star_elm'),
    url('form/', views.StarFormView.as_view(), name='star_form'),
    url('list/$', views.StarListView.as_view(), name='star_list'),
    url('([\d-]+)/$', views.StarView.as_view(), name='star')
]

happiness_star/models.py
from django.db import models
from django.conf import settings
from django.core.exceptions import ValidationError


def one_to_five(number):

    if number < 1 or number > 5:
        raise ValidationError('Must be between 1 and 5')

def lowercase_alphanumeric(text):
    """Ensure text is lowercase, alphanumeric"""

    if type(text) is not str:
        raise ValidationError('Must be str')

    if not text.islower() and text.isalnum():
        raise ValidationError('Must be lowercase letters and numbers')


class Star(models.Model):

    class Meta:
        unique_together = ('user', 'date')

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date = models.DateField()

    spirit = models.IntegerField('energy / spirit', validators=[one_to_five])
    exercise = models.IntegerField(validators=[one_to_five])
    work = models.IntegerField(validators=[one_to_five])
    play = models.IntegerField(validators=[one_to_five])
    friends = models.IntegerField(validators=[one_to_five])
    adventure = models.IntegerField(
        'romance / adventure', validators=[one_to_five])

    def overall(self):
        return (self.spirit + self.exercise + self.play + self.work +
                self.friends + self.adventure) / 6.0

    def __repr__(self):
        return '<Star user=%s date=%s>' % (self.user.email,
                                           self.date.isoformat())

    def __str__(self):
        return 'user: %s, date: %s, overall: %f' % (
            self.user.username,
            self.date.isoformat(),
            self.overall())

    def __iter__(self):
        return iter([('spirit', self.spirit), ('exercise', self.exercise),
                     ('play', self.play), ('work', self.work),
                     ('friends', self.friends), ('adventure', self.adventure),
                     ('tags', [tag.name for tag in self.tag_set.all()]),
                     ('date', self.date.isoformat())])


class Tag(models.Model):

    name = models.CharField(max_length=64, unique=True,
                            validators=[lowercase_alphanumeric])
    star = models.ManyToManyField(Star)

    def __repr__(self):
        return '<Tag name=%s>' % (self.name,)

    def __str__(self):
        return '%s' % (self.name,)

happiness_star/forms.py
from django import forms
from .widgets import StarSelect
from .models import Star

one_to_five = tuple([(i, i) for i in range(1, 6)])


class StarForm(forms.ModelForm):

    class Meta:
        model = Star
        fields = ['spirit', 'exercise', 'play', 'work', 'friends', 'adventure']

    spirit = forms.IntegerField(
        label="Energy / spirit",
        widget=StarSelect(choices=one_to_five, attrs={'class': 'star_radio'}))
    exercise = forms.IntegerField(widget=StarSelect(
        choices=one_to_five, attrs={'class': 'star_radio'}))
    play = forms.IntegerField(widget=StarSelect(
        choices=one_to_five, attrs={'class': 'star_radio'}))
    work = forms.IntegerField(widget=StarSelect(
        choices=one_to_five, attrs={'class': 'star_radio'}))
    friends = forms.IntegerField(widget=StarSelect(
        choices=one_to_five, attrs={'class': 'star_radio'}))
    adventure = forms.IntegerField(
        label="Romance / adventure",
        widget=StarSelect(choices=one_to_five, attrs={'class': 'star_radio'}))

happiness_star/views.py
from django.shortcuts import get_object_or_404
from django.views import View
from django.views.generic import DetailView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.utils import timezone

from dateutil.parser import parse

from user_extensions import utils

from .models import Star
from .forms import StarForm


class StarView(LoginRequiredMixin, DetailView):
    '''View the star for a given date.'''

    contect_object_name = 'star'
    login_url = 'login'
    template_name = 'happiness_star/star.html'

    def get_object(self):
        user = self.request.user
        star_date = parse(self.args[0])
        star = get_object_or_404(Star, date=star_date, user=user)
        return star


class StarListView(LoginRequiredMixin, ListView):
    '''List the stars for a given user.'''

    context_object_name = 'star_list'
    login_url = 'login'
    template_name = 'happiness_star/star_list.html'

    def get_queryset(self):
        return Star.objects.filter(user=self.request.user)


class StarFormView(LoginRequiredMixin, View):
    '''Allow the user to create a star.'''

    form_class = StarForm
    template_name = 'happiness_star/star_form.html'
    star_date = timezone.localdate(timezone.now())

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():

            try:
                star = Star.objects.get(user=request.user, date=self.star_date)
            except Star.DoesNotExist:
                star = Star(user=request.user, date=self.star_date)

            for f in form.cleaned_data:
                setattr(star, f, form.cleaned_data[f])

            star.save()
            status = 200

        else:
            status = 400

        return render(request, self.template_name,
                      {'form': form, 'date': self.star_date}, status=status)

    def get(self, request, *args, **kwargs):

        try:
            star = Star.objects.get(user=request.user, date=self.star_date)
        except Star.DoesNotExist:
            star = None

        if star is not None:
            initial = dict(star)
        else:
            initial = {}

        form = self.form_class(initial=initial)

        return render(request, self.template_name,
                      {'form': form, 'date': self.star_date})


class StarElmView(LoginRequiredMixin, View):
    '''Display the Elm + GQL interface'''

    template_name = 'happiness_star/elm-star.html'

    def get(self, request, *args, **kwargs):
        user = self.request.user
        token = utils.user_jwt(user)
        return render(
            request, self.template_name, {'token': token}, status=200)

happiness_star/templates/happiness_star/elm-star.html
{% extends "base.html" %}

{% block content %}
<div id="star"></div>
{% endblock content %}

{% block scripts %}
<script src="/static/happiness_star/elm-star.js"></script>
<script type="text/javascript">
var elmDiv = document.getElementById("star");
var app = Elm.Main.embed(elmDiv, "{{ token }}");
console.log("{{ token }}");
</script>
{% endblock scripts %}

happiness_star/templates/happiness_star/star.html
{% extends "base.html" %}

{% block content %}
<h1>Star ratings for {{ star.date.isoformat }}</h1>

<table>
<thead>
    <tr><th>Point</th><th>Rating</th></tr>
</thead>
<tbody>
    <tr><td>Spirit</td><td>{{ star.spirit }}</td></tr>
    <tr><td>Exercise</td><td>{{ star.exercise }}</td></tr>
    <tr><td>Play</td><td>{{ star.play }}</td></tr>
    <tr><td>Work</td><td>{{ star.work }}</td></tr>
    <tr><td>Friends</td><td>{{ star.friends }}</td></tr>
    <tr><td>Adventure</td><td>{{ star.adventure }}</td></tr>
    <tr><td>Overall</td><td>{{ star.overall }}</td></tr>
</tbody>
</table>

<h2>Tags</h2>
<ul>
    {% for tag in star.tag_set.all %}
    <li>{{ tag.name }}</li>
    {% endfor %}
</ul>

{% endblock content %}

happiness_star/templates/happiness_star/star_form.html
{% extends "base.html" %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static '/happiness_star/stars.css' %}">
{% endblock style %}

{% block content %}
<form action="{% url 'happiness_star:star_form' %}" method="post">
{% csrf_token %}

<table id="star_form">
<tbody>
<thead>
    <tr><th></th><th colspan="5"><h1>Stars for {{ date.isoformat }}</h1></th></tr>
    <tr><th>Aspect</th><th>1</th><th>2</th><th>3</th><th>4</th><th>5</th></tr>
</thead>
{% for field in form %}
<tr class="star_attribute">

<td>
    <label for="{{ field.id_for_label }}">
    {{ field.label }}</label>
    {% if field.errors %}
        {{ field.errors }}
    {% endif %}
</td>

{% for radio in field %}
<td>{{ radio }}</td>
{% endfor %}
</tr>
{% endfor %}
<tr>
    <td colspan="5"></td>
    <td><input type="submit" value="save" id="star_form_submit" /></td>
</tr>

</tbody>
</table>

</form>
{% endblock content %}

happiness_star/templates/happiness_star/star_list.html
{% extends "base.html" %}

{% block content %}

<table>
<thead>
    <tr><th>Date</th><th>Overall rating</th></tr>
</thead>
<tbody>
{% for star in star_list %}
<tr>
    <td>
        <a href="{% url 'happiness_star:star' star.date %}">
        {{ star.date }}
        </a>
    </td>
    <td>{{ star.overall }}</td>
</tr>
{% endfor %}
</tbody>
</table>

{% endblock content %}

happiness_star/templates/happiness_star/widgets/star_radio_option.html
{% include "django/forms/widgets/input.html" %}
<label{% if widget.attrs.id %} for="{{ widget.attrs.id }}"{% endif %}></label>